version: '3'
services:

  ros-service:
    build: .
    runtime: nvidia

    volumes:
      - ./:/capstone
      - /tmp/log:/root/.ros/

    ports:
      - 4567:4567

  capstone:
    build: .
    runtime: nvidia

    volumes:
      - ./:/capstone
      - /tmp/log:/root/.ros/

    ports:
      - 4567:4567